# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Elite Hackers Site
title-header: Elite Hackers Site
email: schiz0id@elite-hackers.com
description: > # this means to ignore newlines until "baseurl:"
  The best hacking site on the internet. Come here to find out how to become
  a hacker and learn how to hack servers, firewalls, web sites, email accounts, 
  facebook, twitter, and more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://elite-hackers.com" # the base hostname & protocol for your site
twitter_username: schiz0id
github_username:  schiz0id

excerpt_separator: <!--more-->

amazon_tracking_id: "theelihacsit-20"

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /tutorials/:slug/
  books:
    output: true
    permalink: /resources/books/:slug/
  wallpapers:
    output: false
    permalink: /downloads/wallpapers/:slug/
  dictionary_terms:
    output: false
    permalink: /dictionary/:slug/
